name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: Install CMake
      run: sudo apt-get update && sudo apt-get install -y cmake
    - run: |
        chmod +x ./gradlew
        ./gradlew :module:assembleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: Zygisk-Test-2
        path: module/build/outputs/apk/release/
